### ISSUE TITLE
antidebug_antivm has odd rules

### ISSUE THREAD

**Issue by iangcarroll** [Yara-Rules/rules#101]
`antidebug_antivm.yar` has a lot of very odd rules which will match with virtually all programs, like `persistence` and `create_process`: https://github.com/Yara-Rules/rules/blob/4740135a3c5b14ff4ba285b5e780a2b238fa23e6/antidebug_antivm.yar#L927

Doesn't make much sense for those to be in there.

**Comment by mmorenog** [comment]
Thank you. We have commented this rules.
