### ISSUE TITLE
Consider using the Apache License V2

### ISSUE THREAD

**Issue by mmorenog** [Yara-Rules/rules#124]
https://twitter.com/TigzyRK/status/742297040542150657

**Comment by plutec** [comment]
A help:
http://choosealicense.com/licenses/

**Comment by mmorenog** [comment]
Thank you Plutec

**Comment by Neo23x0** [comment]
Please be aware that merging YARA rules from repositories using the GPL would become impossible then.

**Comment by mmorenog** [comment]
At the moment We will continue using GPL license.
