### ISSUE TITLE
rule name prefix

### ISSUE THREAD

**Issue by hegga** [Yara-Rules/rules#125]
Hi,

Thank you for a great repository of yara rules!
Would you consider adding a prefix to the yara rules, so that one can avoid naming collisions when
merging several repositories of yara rules? For example:

rule yararules.com_%rule_name%

**Comment by jovimon** [comment]
Hello hegga,

We will review your suggestion to add a fixed prefix to every rule name to avoid name collisions. 

In the meantime I built this oneliner that, when executed in a shell, will give you a file with all our ruleset, adding a prefix to all the rule names:
`find /path/to/rules/ -type f -name "*.yar*" -exec sed "s/^rule /rule yararules.com_/g" {} \; > ~/full_yararules.com_ruleset.yar`

When you merge several repositories, are all other repositories public? Maybe we have already merged them into our repository. Also if they are not merged we can try to merge them.

Regards,

Jose.
