### ISSUE TITLE
android_meterpreter - a lot of false positives

### ISSUE THREAD

**Issue by c904370** [Yara-Rules/rules#128]
Hello,
First of all - great work with creating and sorting the published YARA rules!

I think there is a problem with android_meterpreter rule (in Android_Metasploit.yar - https://github.com/Yara-Rules/rules/blob/master/Mobile_Malware/Android_Metasploit.yar).

It produces very false positives.

I think that maybe the line:
any of ($check*) or any of ($stop*)

should be changed to:
any of ($check*) and any of ($stop*)

Regards!

**Comment by mmorenog** [comment]
Thank you, we will to check your pull ASAP.
