### ISSUE TITLE
Create combined yar files for different categories

### ISSUE THREAD

**Issue by c904370** [Yara-Rules/rules#133]
Hi,
It will be great if there are combined yar files for different categories (e.g. malware.yar which combines all malware rules from https://github.com/Yara-Rules/rules/tree/master/malware).

The goal is to make it simple to use all of them with clamav-unofficial-sigs (https://github.com/extremeshok/clamav-unofficial-sigs). Right now, every file should be added in the config file separately.

If there are combined files, it will be more easier to use them and if there are new signatures - they will be added automatically.

Thanks in advance!

**Comment by vlad-s** [comment]
You can easily do this by using `cat`, be it by reading the input from `ls` or `find`. Keeping track of a combined rules file in the repo will mean having to manually check and concat the file to the combined one, then adding it to the repo, thus unneeded effort for a single file. In my opinion, any user should combine their own rules when needed, especially when `yara` can read the rules from stdin (your case - clamav - is a special one).

**Comment by Xumeiquer** [comment]
A set of indeces have been added. You can now use a index_gen.sh to generate indeces or at least ensure indices will be created when executed.
Commit ae82fb6e1e3145a85f52c4856985f7743796aae6
