### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by mmorenog** [Yara-Rules/rules#139]
Creación de un index. Sería interesante tener un index por categoría y un index de categorías

**Comment by jholgui** [comment]
No acabo de ver las ventajas de añadir los index como los planteas ..

**Comment by Xumeiquer** [comment]
¿Cuantos indices son necesarios? ¿Un indice principal que aglutine todas las reglas o uno por cada grupo de reglas? ¿Ambas opciones?

**Comment by Xumeiquer** [comment]
Se ha añadido un índice general  incluyendo todas las reglas y uno por cada una de las categorias (carpetas).
Fixed in ae82fb6e1e3145a85f52c4856985f7743796aae6
