### ISSUE TITLE
Rules for AdGholas Malvertising Campaigns

### ISSUE THREAD

**Issue by c904370** [Yara-Rules/rules#142]
Hi,

Here is a write-up for AdGholas Malvertising Campaigns:

https://www.proofpoint.com/us/threat-insight/post/massive-adgholas-malvertising-campaigns-use-steganography-and-file-whitelisting-to-hide-in-plain-sight

At the end of the article, some yara rules are provided.
It would be great if they are included in the yara-rules reopository

**Comment by mmorenog** [comment]
Done! Thank you ! :D
