### ISSUE TITLE
Duplicities

### ISSUE THREAD

**Issue by xambroz** [Yara-Rules/rules#146]
Hello, 
I have found some duplicities in the different yara files, which makes it difficult to compile ruleset with con-cating all or some of the Yara-Rules files.
The RAT_Ratdecoders.yar and MALW_Miscelanea.yar seems to be in collision (assuming that Miscelanea.old should not be used at all).

I would recommend to remove the affected rules from the MALW_Miscelanea.yar as it seems these have been categorized already in the RAT_Ratdecoders.yar

$ for I in PythoRAT VirusRat Ap0calypse Arcom Bandook DarkRAT Greame LostDoor LuxNet Pandora Paradox Punisher SmallNet ; do grep -R "rule[ \t]*$I" * ; done
Yara-Rules/malware/Miscelanea.old:rule PythoRAT
Yara-Rules/malware/RAT_Ratdecoders.yar:rule PythoRAT : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule PythoRAT
Yara-Rules/malware/Miscelanea.old:rule VirusRat
Yara-Rules/malware/RAT_Ratdecoders.yar:rule VirusRat : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule VirusRat
Yara-Rules/malware/Miscelanea.old:rule Ap0calypse
Yara-Rules/malware/RAT_Ratdecoders.yar:rule Ap0calypse: RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule Ap0calypse
Yara-Rules/malware/Miscelanea.old:rule Arcom
Yara-Rules/malware/RAT_Ratdecoders.yar:rule Arcom : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule Arcom
Yara-Rules/malware/Miscelanea.old:rule Bandook
Yara-Rules/malware/RAT_Ratdecoders.yar:rule Bandook : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule Bandook
Yara-Rules/malware/Miscelanea.old:rule DarkRAT
Yara-Rules/malware/RAT_Ratdecoders.yar:rule DarkRAT : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule DarkRAT
Yara-Rules/malware/Miscelanea.old:rule Greame
Yara-Rules/malware/RAT_Ratdecoders.yar:rule Greame : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule Greame
Yara-Rules/malware/Miscelanea.old:rule LostDoor
Yara-Rules/malware/RAT_Ratdecoders.yar:rule LostDoor : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule LostDoor
Yara-Rules/malware/Miscelanea.old:rule LuxNet
Yara-Rules/malware/RAT_Ratdecoders.yar:rule LuxNet : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule LuxNet
Yara-Rules/malware/Miscelanea.old:rule Pandora
Yara-Rules/malware/RAT_Ratdecoders.yar:rule Pandora : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule Pandora
Yara-Rules/malware/Miscelanea.old:rule Paradox
Yara-Rules/malware/RAT_Ratdecoders.yar:rule Paradox : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule Paradox
Yara-Rules/malware/Miscelanea.old:rule Punisher
Yara-Rules/malware/RAT_Ratdecoders.yar:rule Punisher : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule Punisher
Yara-Rules/malware/Miscelanea.old:rule SmallNet
Yara-Rules/malware/RAT_Ratdecoders.yar:rule SmallNet : RAT
Yara-Rules/malware/MALW_Miscelanea.yar:rule SmallNet

Best regards
Michal Ambroz

**Comment by jholgui** [comment]
Duplicate rules deleted.
 
Thank you @xambroz
