### ISSUE TITLE
Misp

### ISSUE THREAD

**Issue by mmorenog** [Yara-Rules/rules#152]
https://twitter.com/MISPProject/status/760721575859609600

**Comment by plutec** [comment]
How we can do that? MISP module but... you need to run Yara on MISP server?

**Comment by mmorenog** [comment]
I think that Radare supports MISP, and also supports Yara...maybe It's possible to do some kind of integration Radare <-> Yara <-> MISP

**Comment by seifreed** [comment]
https://twitter.com/akochkov/status/768066759207350273

**Comment by Te-k** [comment]
I have developed a simple script to do this : https://github.com/Te-k/analyst-scripts/blob/master/misp/yaraxcheck.py

**Comment by jovimon** [comment]
Thank you very much @Te-k for your great work.
