### ISSUE TITLE
Review base64 rule, it seems to fire a lot of false positives

### ISSUE THREAD

**Issue by Xumeiquer** [Yara-Rules/rules#153]

**Comment by barakshelef** [comment]
This rule will raise a false positive on almost any file containing a ASCII string longer than 4 chars:

1. It could check if beyond the match there are any base64 that could mess up the padding. ie:
`aGVs` will fire, and so will `aGVsbG8gd29ybGQ=`; but also will this `$aGVsF$` ($ just to represent a non-base64 char). If the regex would make sure there are no additional b64 chars outside of the legal padding it'll be much more effective handling normal strings in a file.

2. Give it a minimal length. A single 4 block is only 3 bytes of encoded data. In a quick test i found that in a randomly generated 100 MB file I got over 300K matches when allowing even a single block (1.17% of the data). by changing to `/([A-Za-z0-9+\/]{4}){2,}([A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?/` i got it down to 1213 matches (<0.01%), and by increasing to `{3,}` i got only 4 matches out of 100MB of random data. This means this rule might miss out on base64 encoded data shorter than 9 bytes - but should rarely fire on any binary data.

**Comment by xambroz** [comment]
I agree with barakshelef ... still too many positives to be included in the overall indexes of index.yar / Crypto_index.yar / index_w_mobile.yar
