### ISSUE TITLE
Duplicate rules and invalid field name

### ISSUE THREAD

**Issue by mhoanginfoblox** [Yara-Rules/rules#163]
./Crypto/crypto_signatures.yar(407): duplicated identifier "DarkEYEv3_Cryptor"
./Mobile_Malware/Android_OmniRat.yar(19): invalid field name "activity"
./Packers/peid.yar(32474): duplicated identifier "MinGW"
./Mobile_Malware/Android_OmniRat.yar(19): invalid field name "activity"

**Comment by mhoanginfoblox** [comment]
I have another error:

./Mobile_Malware/Android_MazarBot_z.yar(31): invalid field name "certificate"

**Comment by xambroz** [comment]
Yara-Rules/./Crypto/crypto_signatures.yar(238): error: duplicated identifier "BLOWFISH_Constants"
Yara-Rules/./Crypto/crypto_signatures.yar(261): error: duplicated identifier "MD5_Constants"
Yara-Rules/./Crypto/crypto_signatures.yar(299): error: duplicated identifier "RC6_Constants"
Yara-Rules/./Crypto/crypto_signatures.yar(316): error: duplicated identifier "RIPEMD160_Constants"
Yara-Rules/./Crypto/crypto_signatures.yar(337): error: duplicated identifier "SHA1_Constants"
Yara-Rules/./Crypto/crypto_signatures.yar(360): error: duplicated identifier "SHA512_Constants"
Yara-Rules/./Crypto/crypto_signatures.yar(392): error: duplicated identifier "WHIRLPOOL_Constants"
Yara-Rules/./Crypto/crypto_signatures.yar(407): error: duplicated identifier "DarkEYEv3_Cryptor"

Duplicates in:
Yara-Rules/Crypto/crypto.yar
Yara-Rules/Crypto/crypto_signatures.yar

**Comment by mmorenog** [comment]
Deleted crypto.yar

Check:
./Mobile_Malware/Android_OmniRat.yar(19): invalid field name "activity"
./Packers/peid.yar(32474): duplicated identifier "MinGW"
./Mobile_Malware/Android_MazarBot_z.yar(31): invalid field name "certificate"

**Comment by mmorenog** [comment]
Solved this issue: ./Packers/peid.yar(32474): duplicated identifier "MinGW" 

Hi Minh, in regard to this issue:
./Mobile_Malware/Android_OmniRat.yar(19): invalid field name "activity"
./Mobile_Malware/Android_MazarBot_z.yar(31): invalid field name "certificate"

we aren't detecting these errors, are you import "androguard" module correctly?

Regards,

**Comment by plutec** [comment]
I checked the problem with Android_OmniRat and Android_MazarBot_z and there is no reason to fail. Did you compile yara with Androguard module? https://github.com/Koodous/androguard-yara
Do you have any more information about your yara compilation? (version, compiled modules, ...)

**Comment by xambroz** [comment]
Another new duplicity
Yara-Rules/./Mobile_Malware/Android_Marcher_2.yar(1): error: duplicated identifier "marcher"

$ grep -R marcher Yara-Rules/
Yara-Rules/Mobile_Malware/Amtrckr_20160519.yar:rule marcher: amtrckr
Yara-Rules/Mobile_Malware/Android_Marcher_2.yar:rule marcher

**Comment by mhoanginfoblox** [comment]
Thank you everyone for quick reply. I do not have androguard, I create another index.yar without the Mobile_Malware and it works

**Comment by mmorenog** [comment]
Solved xambroz! Thanks!!!
