### ISSUE TITLE
Ransom yara rules

### ISSUE THREAD

**Issue by mmorenog** [Yara-Rules/rules#167]
rule Ransom_Alpha
{
    meta:
        description = "Regla para detectar Ransom.Alpha"
        author = "CCN-CERT"
        version = "1.0"
    strings:
	$a = { 52 00 65 00 61 00 64 00 20 00 4D 00 65 00 20 00 28 00 48 00 6F 00 77 00 20 00 44 00 65 00 63 }
    condition:
        $a
}

rule Ransom_Alfa
{
    meta:
        description = "Regla para detectar W32/Filecoder.Alfa"
        author = "CCN-CERT"
        version = "1.0"
    strings:
	$a = { 8B 0C 97 81 E1 FF FF 00 00 81 F9 19 04 00 00 74 0F 81 F9 } 
	$b = { 22 04 00 00 74 07 42 3B D0 7C E2 EB 02 }
    condition:
	all of them
}

**Comment by seifreed** [comment]
Hi,

Testing, yara Rules

Regards,

**Comment by seifreed** [comment]
The yara rules are not matching with Alpha Ransomware.

Ransom_Alpha:e2b5035871075f8ba2b621dd7d7b6382b277fa1e1ecfa3401ef7628cd0fe9438
Ransom_Alpha:9f9f368b692fb6e9ba876df007de0f44ae10a841504d4449616f38ecc402dee2
Ransom_Alpha:b897f9ba657522028c38ba260da17c58c8f75e4e7faca75e681f4c4cb60b90c9
Ransom_Alpha:0dd2ab09ff83f730b3f42bd716676e8b9caca464385d36d1e66cf9d13473f669

One of them it's the decrypter for Alpha ransomware. The others are other type of malware.

**Comment by mmorenog** [comment]
Añado comentario en el fichero.
