### ISSUE TITLE
More liberal licensing?

### ISSUE THREAD

**Issue by adewes** [Yara-Rules/rules#177]
Hey, first of all: This is a great project! I wonder though why you chose GPL as a license, as this will make it very difficult to use the data in many situations.

I'd like to suggest thinking about publishing the rules under a more permissive license. Personally, I think a database license like one from http://opendatacommons.org/licenses/ , or a Creative Commons license would make more sense for a rule database, as it's not really software that you're sharing but patterns/data. I don't know what your intent is with the rule database so I'm not able to provide a recommendation for a license (and maybe GPL does indeed fit your intended use case best), I just wanted to point out that using GPL will make it more difficult for people to use the rules, which is really a pity.

**Comment by Xumeiquer** [comment]
Hi adewes,
We are thinking about it and it's difficult to chose what license fits best to the rules repository, but for now as we are using some GPL rules we need to use that license.

We apreciate your opinion, thanks.

**Comment by Neo23x0** [comment]
I was thinking about changing my license to 
CC BY-NC-SA 4.0 
https://creativecommons.org/licenses/by-nc-sa/4.0/

@adewes: Would this solve the problems that you see in the GPL?

**Comment by adewes** [comment]
@Neo23x0 I think companies would not be able to use the rules if they have a non-commercial license (e.g. it is hard to argue if using them to defend against malware would alread constitute commercial usage). I think a license that is "non-contagious" and allows use without restrictions would be the best. For my software projects I usually use the MIT license, but I'm not sure if this is appropriate for a rule repository, hence my link to the OpenDataCommons, which might be more fitting.

**Comment by cocowalla** [comment]
@Xumeiquer has any more thought gone into the license? Unfortunately, many companies won't go near anything released under GPL
