### ISSUE TITLE
Rest services

### ISSUE THREAD

**Issue by agaglia** [Yara-Rules/rules#182]
Hi, I have seen https://analysis.yararules.com/ and I found it very interesting. There is a chance to put the Rest API services for integration with Cuckoo?
Thank you

**Comment by Xumeiquer** [comment]
Hi @agaglia 
We are working on improvements and the Rest API is one of them so you could integrate Yaralyzer with a lot of software. We hope to have a new release soon. 

Thanks for the advice and thank you for using the tool.
