### ISSUE TITLE
APT29 Grizzly Steppe

### ISSUE THREAD

**Issue by Xumeiquer** [Yara-Rules/rules#192]
https://twitter.com/cyb3rops/status/814769499555659776?s=09

https://github.com/Neo23x0/signature-base/blob/master/yara/apt_apt29_grizzly_steppe.yar
http://pastebin.com/gxq0FMsU

**Comment by mmorenog** [comment]
APT29 Grizzly Steppe YARA rules
https://github.com/Neo23x0/signature-base/blob/master/yara/apt_apt29_grizzly_steppe.yar …
Other samples
http://pastebin.com/gxq0FMsU 
@JGamblin @USCERT_gov

**Comment by mmorenog** [comment]
Merged
