### ISSUE TITLE
Comment via @MalwareMechanic on Twitter

### ISSUE THREAD

**Issue by mmorenog** [Yara-Rules/rules#197]
Hey YaraRules, "rule InstallShield2000" at https://t.co/e9C9ULlHBp should be removed from packer.yar as it's actually the entry point asm for Visual C++ 5.0. The same incorrect rule can be found in https://t.co/aFV1i5oLYr and is called "rule InstallShield_2000". Seems x64dbg fixed it at https://t.co/RmIUOL6wau. The signature should belong in a compiler signature file. Thanks!

**Comment by seifreed** [comment]
Done

https://github.com/Yara-Rules/rules/commit/10ec5e8887de65ea20ceafd01be290f952f2a3b4
https://github.com/Yara-Rules/rules/commit/4fe01a0c1b39aedb9a804a13f038552d3640702e
