### ISSUE TITLE
Android Yara Rule

### ISSUE THREAD

**Issue by mmorenog** [Yara-Rules/rules#198]
Shivang Desai (@5h1vang) twitteó a las 7:30 a. m. on mié., ene. 04, 2017:
#Android #Malware @yararules @koodous_project  #superMario
rule:https://t.co/TYErcxKIn0
src:https://t.co/Xxu4F1kcE7
(https://twitter.com/5h1vang/status/816532304621408256?s=03)

**Comment by seifreed** [comment]
Commited:

https://github.com/Yara-Rules/rules/commit/4dd667a330c693b4f2f8cb3b3137e7657eb41695
