### ISSUE TITLE
Guidelines for contribution

### ISSUE THREAD

**Issue by elhoim** [Yara-Rules/rules#20]
It might interesting to create guidelines for contribution to try to normalize some of the things.
For example:
- use of namespaces;
- use of yara modules;
- date format (04-Apr-15 / 04-05-2015 / etc...);
- name of the meta field(s) used to store hashes (md5/sha256/reference/hash).

**Comment by jholgui** [comment]
Yes, we have to define this very soon. After, we have to change the rules to this guidelines.
