### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by seifreed** [Yara-Rules/rules#200]
https://github.com/abhinavbom/Yara-Rules/blob/master/virustotal-rules.yara

**Comment by asingh270** [comment]
is this added to official repo ?

**Comment by mmorenog** [comment]
Just now :)

(Note that these rules are not enabled, you have to enabled them)

Thank you

**Comment by mmorenog** [comment]
https://github.com/Yara-Rules/rules/blob/master/utils/virustotal.yar
