### ISSUE TITLE
SpyeEye Creating false positives

### ISSUE THREAD

**Issue by GelosSnake** [Yara-Rules/rules#204]
The rules over this spesefic RAT are too reflexive
Example: 
md5,5E95F62355B050F7E739FA3660A7CC74
spyeye jq-win64.exe
0x23734d:$f: data_end 

rule spyeye : banker
{
	meta:
		author = "Jean-Philippe Teissier / @Jipe_"
		description = "SpyEye X.Y memory"
		date = "2012-05-23" 
		version = "1.0" 
		filetype = "memory"

	strings:
		$spyeye = "SpyEye"
		$a = "%BOTNAME%"
		$b = "globplugins"
		$c = "data_inject"
		$d = "data_before"
		$e = "data_after"
		$f = "data_end"
		$g = "bot_version"
		$h = "bot_guid"
		$i = "TakeBotGuid"
		$j = "TakeGateToCollector"
		$k = "[ERROR] : Omfg! Process is still active? Lets kill that mazafaka!"
		$l = "[ERROR] : Update is not successfull for some reason"
		$m = "[ERROR] : dwErr == %u"
		$n = "GRABBED DATA"
		
	condition:
		$spyeye or (any of ($a,$b,$c,$d,$e,$f,$g,$h,$i,$j,$k,$l,$m,$n))
}

**Comment by seifreed** [comment]
Hey Snake, thanks for your feedback

You have any advice about how to improve it?

Regards,
--
Marc Rivero López | @seifreed | ecrime.pro

**Comment by seifreed** [comment]
hey @GelosSnake we will close the issue if we don't have any reply from you

:)

**Comment by seifreed** [comment]
Closing to not have reliable feedback

**Comment by MartinEmrich** [comment]
Many years later, I have the same issue (Trying out "TreadMapper", which apparently uses this rule set).

An obvious improvement would be to remove at least these extremely generic strings:

````
	$d = "data_before"
	$e = "data_after"
	$f = "data_end"
````
