### ISSUE TITLE
EICAR?

### ISSUE THREAD

**Issue by egberts** [Yara-Rules/rules#207]
Do we need a Yara signature for EICAR test pattern?

**Comment by seifreed** [comment]
Do you want to propose something? @egberts

**Comment by seifreed** [comment]
done 

https://github.com/Yara-Rules/rules/commit/2575c29ee12c4e2704025a001cb47230796ab4bf

**Comment by frikilax** [comment]
hey @seifreed  ! Thanks for adding this rule, this is great for testing Yara implementations !

Sorry for bringing that up today, but I've began to play with those rules and found out you didn't give a file extension to the EICAR rule file, is there a reason for that ?
