### ISSUE TITLE
SWF files removed

### ISSUE THREAD

**Issue by wpeasycart** [Yara-Rules/rules#208]
We are having clients tell us that when they install our legitimate SWF files used for administrative tools and consoles that they are removed automatically by this process.  Is there a way around having all SWF files blanket removed?

**Comment by jovimon** [comment]
Hello @wpeasycart. 
We do not provide any software, only the rules to be checked. 
There are more general rules and more specific ones, but it is up to the people performing the checks to decide what to do with the files detected by our rules.
Maybe you should ask your clients' hosting provider ...

**Comment by seifreed** [comment]
Closed the issue due is resolved
