### ISSUE TITLE
Duplicate Rule Install_Shield_2000?

### ISSUE THREAD

**Issue by brifordwylie** [Yara-Rules/rules#211]
New to Yara, so if this is pilot error feel free to close :)

```
$ python -c 'import yara; print(yara.__version__)'
3.5.0
```
So when I'm compiling the rules:
```
yara.compile('/path/to/yara/index.yar')
```

I get this error:
```
yara.SyntaxError: yara_rules/./Packers/peid.yar(28886): duplicated identifier "Install_Shield_2000"
```

So doing a grep I get:
```
$ grep -A 6 -r --include="*.yar" Install_Shield_2000 .
./Packers/packer.yar:rule Install_Shield_2000
./Packers/packer.yar-{
./Packers/packer.yar-	meta:
./Packers/packer.yar-		author = "PEiD"
./Packers/packer.yar-		description = "Microsoft Visual C++ 5.0"
./Packers/packer.yar-		group = "15"
./Packers/packer.yar-		function = "16"
--
./Packers/peid.yar:rule Install_Shield_2000
./Packers/peid.yar-{
./Packers/peid.yar-	meta:
./Packers/peid.yar-		author = "PEiD"
./Packers/peid.yar-		description = "Microsoft Visual C++ 5.0"
./Packers/peid.yar-		group = "15"
./Packers/peid.yar-		function = "16"
```

Shrug... is this a bug or just pilot error? Should I compile the rules a different way?

**Comment by seifreed** [comment]
Hey @brifordwylie that was my fault, because I didn't generate the index again.

Can you try now?

**Comment by brifordwylie** [comment]
@seifreed there's still have a duplicate. Regenerating the index file isn't going to fix a duplicate (see info above).  I think the real solution is to remove one of the Install_Shield_2000 rules. It's the exact same rule in both packer.yar and peid.yar
