### ISSUE TITLE
Install_Shield_2000 named twice

### ISSUE THREAD

**Issue by timstoop** [Yara-Rules/rules#216]
Next error I encounter:
```
tim@:~/workspace/rules$ sudo yara -w -r index.yar /srv
./malware/MALW_AdGholas.yar(80): error: internal fatal error
./Packers/peid.yar(28886): error: duplicated identifier "Install_Shield_2000"
```
(I know about the first one, need to recompile yara, sadly.)

That second error is indeed a duplicate:

```
tim@:~/workspace/rules$ rgrep Install_Shield_2000
Packers/packer.yar:rule Install_Shield_2000
Packers/peid.yar:rule Install_Shield_2000
```

The definitions look to be duplicates to my (very untrained) eye as well. My index.yar was created with index_gen.sh, not sure if I should exclude either of these files.

**Comment by mmorenog** [comment]
Thank you. Fixed in https://github.com/Yara-Rules/rules/pull/226
