### ISSUE TITLE
Rule Wanna_Cry_Ransomware_Generic - False positives

### ISSUE THREAD

**Issue by zbetcheckin** [Yara-Rules/rules#232]
Beware, the rule Wanna_Cry_Ransomware_Generic generates too many false positives.

The rule matches with these few examples :

Cerber :
e5ad03ba99211cf85d931f0ae0ae5758
35994e030e525078768ca3b9d3072a00
509bc889f9408d7a7ef7c93b7f5eca6e 
5f75b3512a4d66a4724ad19afd110319
df3ee045ee4d92f5a7772299651039f7

Kovter :
1adbe29a4370d04f549c7022964d42db 

Other samples that are not WannaCry but match but this rule :
f9c3070b98b4a53117b8687aac9c4dc5 
b878008e875dd0d73692a73d05e3c6fb
334e9659c06dbbd347ae1624246386db
11e6e9b5f43fb173a1f86a7442c3e0d9
917d1027b96cb526fa626335cca479c8

I was not able to fix it by myself. Is there a problem with the 'or' conditions?

```
rule Wanna_Cry_Ransomware_Generic
{
meta:
description = "Detects WannaCry Ransomware on disk and in virtual page"
author = "US-CERT Code Analysis Team"
reference = "not set"
date = "2017/05/12"
hash0 = "4DA1F312A214C07143ABEEAFB695D904"
strings:
$s0 = {410044004D0049004E0024}
$s1 = "WannaDecryptor"
$s2 = "WANNACRY"
$s3 = "Microsoft Enhanced RSA and AES Cryptographic"
$s4 = "PKS"
$s5 = "StartTask"
$s6 = "wcry@123"
$s7 = {2F6600002F72}
$s8 = "unzip 0.15 Copyrigh"
condition:
$s0 and $s1 and $s2 and $s3 or $s4 or $s5 or $s6 or $s7 or $s8
}
```

**Comment by Neo23x0** [comment]
This rule is sh** and yes, there is a problem with the "or" conditions. 
They've updated that rule on their website.

**Comment by mmorenog** [comment]
Thank you. Fixed.
