### ISSUE TITLE
Consider merging RFXN LMD rules into Yararules

### ISSUE THREAD

**Issue by jovimon** [Yara-Rules/rules#233]
As per https://twitter.com/Florent_ATo/status/867109170394353665

RFXN LMD app: https://www.rfxn.com/projects/linux-malware-detect/

I checked and we already have most of them, only missing 69 of 779 (<9%). [Rule names attached](https://github.com/Yara-Rules/rules/files/1036334/missing_rfxn_rules.txt).

Will need to check licenses and find a good place for all the missing rules.

**Comment by Xumeiquer** [comment]
I think we can discard this, because 9% is not as valuable as maintaining the merge between repositories.
