### ISSUE TITLE
Rules in Yara-Rules/email are too generic and cause lot of false positives

### ISSUE THREAD

**Issue by xambroz** [Yara-Rules/rules#238]
Hello,
the rules in Yara-Rules/email are too bread and generate too much of false positives.
For example each EXE files being processed with the Yara-Rules will match 3 rules from this folder:
with_attachment OR without_attachment
with_url OR without_url
with_image OR without_image

As a quick fix for this I created pull request to add some more matching to theese verbose rules to match for the email headers "To:" "From:" "Subject:".

Please consider mergin in this pull request #237. 

Even once merged in it would deserve some more review - for example "without_attachment" will happily trigger for the EML files with MIME multipart - like the Locky style emails with the ZIP attachment and text what to do ... so the name "without_attachment" could be quite misleading when it really means without tag "X-Attachment-id".

Best regards
Michal Ambroz

**Comment by plutec** [comment]
Fixed with commit https://github.com/Yara-Rules/rules/commit/d613c098db5c345e0602621768bd7f6568717bdc

**Comment by xambroz** [comment]
thank you
