### ISSUE TITLE
List of yara rules repositories to integrate

### ISSUE THREAD

**Issue by elhoim** [Yara-Rules/rules#24]
https://github.com/kevthehermit/YaraRules
https://github.com/phbiohazard/Yara
https://github.com/arbor/yara
https://github.com/nyx0/yar4m
https://github.com/3vangel1st/Yara
https://github.com/citizenlab/malware-signatures/blob/master/yara-rules/malware-families/msattacker.yara
https://github.com/jipegit/yara-rules-public
https://github.com/securitykitten/public_yara_rules/tree/master/sandbox_checking
https://github.com/sysforensics/YaraRules
https://github.com/naxonez/yaraRules
https://github.com/Jawn123/YaraRules
https://github.com/AlienVault-Labs/AlienVaultLabs

I know it is not a Pull Request, but I thought it will be easier to split work using an issue.

**Comment by mmorenog** [comment]
https://github.com/kevthehermit/YaraRules OK 
https://github.com/phbiohazard/Yara OK
https://github.com/arbor/yara OK
https://github.com/nyx0/yar4m OK
https://github.com/3vangel1st/Yara OK
https://github.com/citizenlab/malware-signatures/blob/master/yara-rules/malware-families/msattacker.yara OK

**Comment by mmorenog** [comment]
https://github.com/jipegit/yara-rules-public OK
https://github.com/securitykitten/public_yara_rules/tree/master/sandbox_checking OK
https://github.com/sysforensics/YaraRules OK
https://github.com/naxonez/yaraRules OK
https://github.com/Jawn123/YaraRules OK
https://github.com/AlienVault-Labs/AlienVaultLabs OK

Added rules to yararules repository.

Thank you ! :)
