### ISSUE TITLE
HIDDEN COBRA – North Korea’s DDoS Botnet Infrastructure

### ISSUE THREAD

**Issue by jholgui** [Yara-Rules/rules#242]
https://www.us-cert.gov/ncas/alerts/TA17-164A?platform=hootsuite

**Comment by jholgui** [comment]
https://github.com/Yara-Rules/rules/commit/56c8eed904c8cfd03484222102760d65f241b103

**Comment by Neo23x0** [comment]
Don't ... just use US CERT YARA rules without testing. The second rule is prone to false positives.
