### ISSUE TITLE
Ramsonware.yar false positives

### ISSUE THREAD

**Issue by timothycovel** [Yara-Rules/rules#25]
Fairly new to github and this project, so apologies if this is not the proper place to put this.

scanning several hundred files per day, I have found that the rules CryptoLocker_set1 and CryptoLocker_rule2 trigger very frequently on otherwise clean files, as well as malware not related to cryptolocker. They appear to have been made using a yara generator script, which while good can make signaturs that are too generic. 

These two rules are likely to match on a wide range of non-cryptolocker binaries since they only require to match 8 of the listed strings, and there are at least 8 highly generic strings per set. 

I have just stopped including this file in our sandbox, but I thought others should be aware of this.

**Comment by jholgui** [comment]
is it possible to change the rules to have less false positives?

**Comment by SnakeByteIL** [comment]
can you show send me a file with false positives? I can work on it some more.

**Comment by timothycovel** [comment]
Here is one that is dropped by a google updater

http://scanner.metaflows.com/CAUTION/signed_samples/GoogleCrashHandler.exe
https://www.virustotal.com/en/file/90e4352f8a248fa64ea71b8ab07141142b809b384e9f7d1cb7c3dfbf4003bfae/analysis/

# yara -s /root/cuckoo/data/yara/index_binaries.yar GoogleCrashHandler.exe
CryptoLocker_set1 GoogleCrashHandler.exe
0x2a9ab:$string0: static
0x2ad5b:$string0: static
0x37936:$string3: C\x00o\x00m\x00p\x00a\x00n\x00y\x00N\x00a\x00m\x00e\x00
0x37b1e:$string4:
P\x00r\x00o\x00d\x00u\x00c\x00t\x00V\x00e\x00r\x00s\x00i\x00o\x00n\x00
0x34d56:$string7:   </trustInfo>
0x34cf3:$string10:         <requestedExecutionLevel level
0x3789e:$string11:
V\x00S\x00_\x00V\x00E\x00R\x00S\x00I\x00O\x00N\x00_\x00I\x00N\x00F\x00O\x00
0x34c47:$string13: <assembly xmlns
0x34c91:$string14:   <trustInfo xmlns

**Comment by jholgui** [comment]
We have raised the number of strings to match ..
