### ISSUE TITLE
Invalid regex

### ISSUE THREAD

**Issue by jbremer** [Yara-Rules/rules#252]
```
➜  rules git:(master) yara malware/MALW_AdGholas.yar
malware/MALW_AdGholas.yar(15): error: out of space in lex_buf
malware/MALW_AdGholas.yar(80): error: syntax error, unexpected $end, expecting _REGEXP_
```

**Comment by plutec** [comment]
Which version of yara are you using?

**Comment by jbremer** [comment]
`yara-python==3.6.1` :)

**Comment by Xumeiquer** [comment]
This issue is because a limit on regex length imposed by Yara.
By the way I think we should remove this rule as my understanding it does not add anything worthy.

**Comment by jholgui** [comment]
Deleted MALW_AdGholas.yar file.
