### ISSUE TITLE
Global private rule in malware/MALW_Magento_suspicious.yar

### ISSUE THREAD

**Issue by xambroz** [Yara-Rules/rules#265]
Hello,
the file malware/MALW_Magento_suspicious.yar contains globabl private rule named "malware_size".
By yara specification yara executes the global rules first and all the other rules are executed only if the rule is matching. 
So having "malware_size" rule in malware/MALW_Magento_suspicious.yar and having malware/MALW_Magento_suspicious.yar in the overall index.yar/malware_index.yar/index_w_mobile.yar prevents execution of rules in these rulesets to any files bigger than 500KB.

This is quite limiting for bigger malware like hawkey/adwind RAT, wannacry, petya and probably many others.

I would recommend to do one/some of these:
- remove the global private flag from rule malware_size
- remove the malware_size rule from malware/MALW_Magento_suspicious.yar
- modify all the other rules from malware/MALW_Magento_suspicious.yar individually to include this size limit 

Best regards
Michal Ambroz

**Comment by xambroz** [comment]
I originally thought this is some kind of race-condition bug in yara 3.6.2 itself - https://github.com/VirusTotal/yara/issues/700

**Comment by plutec** [comment]
You're right, thanks!
