### ISSUE TITLE
Incorrect rule Webshells

### ISSUE THREAD

**Issue by maxrip** [Yara-Rules/rules#269]
https://analysis.yararules.com/analysis/5979089ae41a9c38fc8688c3
This rule is very extensive, under it comes "verification of rights" installation script.

Offset | String identifier | String data
-- | -- | --
0x523a | $s0 | return $type . $owner . $group . $other;
0x4feb | $s1 | $owner = ($mode & 00400) ? 'r' : '-';

**Comment by Xumeiquer** [comment]
Please could you tell us a little bit more about the issue. It is quite difficult to understand what's the matter.

**Comment by seifreed** [comment]
Hey @maxrip 

If you saw the rule name _(description = "Semi-Auto-generated  - from files webadmin.php.php.txt, iMHaPFtp.php.php.txt, Private-i3lue.php.txt")_, is a rule generated, probably with yargen, so depending your use case couldn't be a valid rule.

I recommend you to contact with @Neo23x0 to improve the rule if you have any idea

**Comment by Neo23x0** [comment]
Just remove the rule. It is a "super rule" and more specific rules exists for the related web shells, which are referenced with their hash.
