### ISSUE TITLE
A lot of FP for MALW_PE_sections.yar

### ISSUE THREAD

**Issue by c904370** [Yara-Rules/rules#275]
Hi,

There are a lot of false positives for MALW_PE_sections.yar when non-PE files are scanned.

As the idea of this rule is to flag a PE files, perhaps adding a condition such as "uint16(0) == 0x457f" will solve this issue.

**Comment by seifreed** [comment]
Can you do a PR? We will review it!

**Comment by mmorenog** [comment]
Thank you!
