### ISSUE TITLE
duplicated identifier "Windows_Malware"

### ISSUE THREAD

**Issue by yntnm** [Yara-Rules/rules#277]
Hii,

There is tow same rule identifier that cause en error , when we use all the rules to scan.

The error; 
> rules/./malware/MALW_Zeus.yar(8): error: duplicated identifier "Windows_Malware"

The rule : malware/MALW_Zeus.yar and malware/MALW_AZORult.yar are those that contain the same identifier.

Thanks for the great job guys

**Comment by mmorenog** [comment]
Solved!

Thank you!
