### ISSUE TITLE
Propuesta

### ISSUE THREAD

**Issue by mmorenog** [Yara-Rules/rules#279]
Nos proponen añadir una nueva categoría que clasifique las firmas por OS.

**Comment by Xumeiquer** [comment]
What is the purpose of this? 

A new category could imply a lot of changes. For example, would it be either a global category which splits up the rules by SO or a sub category inside each category?

I think as a first approach we could use the meta entry with a SO key that identify the targe SO.

**Comment by jholgui** [comment]
We have to set the requirements to yararules rules. I think that to set OS category is very hard and difficult.

**Comment by knowmalware** [comment]
How about instead of operating system, we introduce a "filetype" tag or meta?  For example, if I scan files from a Linux web server, I would want the rules tagged with "elf" and "php".  And if I scan files from a Windows web server, I would want the rules tagged with "pe32" and "php".

**Comment by Xumeiquer** [comment]
Is this still on?

**Comment by knowmalware** [comment]
Do you like my "filetype" tags idea?  If yes, then I will try to apply it to existing rules and submit a PR

**Comment by knowmalware** [comment]
I tried applying filetype or operating system tags to some of the rules.  Unfortunately, this is more complicated than I thought.

What tag do we use if the rule checks for the presence of a particular windows registry key and values?  We would have to label the rule with every possible filetype that could be executed on Windows, including PE32, PowerShell, Python, etc.

If we use operating system tags, what tag do we use if the rule checks for a particular sequence of Intel x86_64 opcodes?  That could be Windows, Linux, macOS, *BSD, etc.

I need to think about this some more.

**Comment by jholgui** [comment]
I think, that it's more interesting set tags to difference memory rules of disk or raw rules.
