### ISSUE TITLE
Duplicated Identifiers errors, "sync" error

### ISSUE THREAD

**Issue by 4n6analist** [Yara-Rules/rules#303]
rules/./malware/MALW_Rebirth_Vulcan_ELF.yar(62): error: duplicated identifier "is__elf"
rules/./malware/MALW_AZORULT.yar(23): error: invalid field name "sync"
rules/./malware/MALW_Mirai_Satori_ELF.yar(27): error: duplicated identifier "is__elf"
rules/./malware/MALW_Httpsd_ELF.yar(42): error: duplicated identifier "is__elf"
rules/./malware/MALW_Mirai_Okiru_ELF.yar(6): error: duplicated identifier "is__Mirai_gen7"
rules/./malware/MALW_Mirai_Okiru_ELF.yar(27): error: duplicated identifier "is__elf"

**Comment by VVinner38** [comment]
You can rename the rules

**Comment by boodera** [comment]
Actually, in file "MALW_AZORULT.yar" its showing "cuckoo.sync.mutex" func as a syntax error.
How this can be resolved if you can give any hint?

**Comment by axpatito** [comment]
Running into the same error while installing on a fresh remnux machine. Has anyone been able to solve this?

**Comment by jholgui** [comment]
@boodera cuckoo support is not by default with yara. If it's important for you this rule you can compile with cuckoo support. I think that in the feature this rules will be disable in yararules.
