### ISSUE TITLE
duplicate rule mumblehard_packer

### ISSUE THREAD

**Issue by SnakeByteIL** [Yara-Rules/rules#31]
https://github.com/Yara-Rules/rules/blob/da9c9b9995bdf0e740e4ea6ce18d01cf2f52e308/malware/Miscelanea_Linux.yar

Is also in packer.yar 
https://github.com/Yara-Rules/rules/blob/master/packer.yar
Is there a reason to keep it in both sections?

**Comment by jholgui** [comment]
We have deleted this rule from Miscelanea_Linux.yar. 
https://github.com/Yara-Rules/rules/commit/58014abeedacfabe92a0b066fe92bdabda1205de#diff-32fb06bd4bdca31c53f6f84ea51f04c6

Thank you @SnakeByteIL

**Comment by SnakeByteIL** [comment]
You welcome
