### ISSUE TITLE
problem cuckoo with this repo 

### ISSUE THREAD

**Issue by rayenmessaoudi** [Yara-Rules/rules#312]
when i m trying to scan a blank pdf file using cuckoo the report.json file is too big (338 MO) due to a lot of external yararules.

ps : i m using this repo for yara rules.
one of the cuckoo developer told me bcz it doesn't it should be splited to categories, memory, files etc which is WIP, but right now is not perfect to get and plug it into the cuckoo

any one can help me to fix the problem.
the report.json can be found here
https://drive.google.com/file/d/1tbkRqRF92X5Ar1gWOmE8lhjXKtS65PJC/view?usp=sharing

**Comment by seifreed** [comment]
Well, you have to modify the rules on your own and add any category you guess could help for your use case!
