### ISSUE TITLE
antidebug_antivm.yar contains rules unrelated to antidebug and antivm

### ISSUE THREAD

**Issue by knowmalware** [Yara-Rules/rules#316]
Some of the rules in the antidebug_antivm.yar file look unrelated to anti-analysis.  From inject_thread down, except for check_patchlevel and vmdetect_misc

**Comment by knowmalware** [comment]
I propose a new Capabilities rule set that contains the rules that are not anti-analysis related.  This rule set would be used for rules that identify capabilities of a file, for example network communication or bitcoin related.  This provides a way to accept rules that do not cleanly fit in other rule sets in the repository.

**Comment by Xumeiquer** [comment]
Could you propose a pull request with the changes?

Thanks.
