### ISSUE TITLE
undefined identifier "is__elf"

### ISSUE THREAD

**Issue by jestrada78** [Yara-Rules/rules#323]
Hello.
When I execute the next command:
>_vol.py -f mem.elf --profile=Win7SP1_24000 yarascan -y c:\rules-master\index.yar_
I get tehe following message:
 ERROR   : volatility.debug    : Cannot compile rules: ./malware/MALW_Mirai_Okiru_ELF.yar(21): **undefined identifier "is__elf**"

I'm new with yara.. 
Thanks in advance

**Comment by jestrada78** [comment]
Please can someone explainme what is this?

**Comment by jovimon** [comment]
Hello @jestrada78,
The [line that generated your error](https://github.com/Yara-Rules/rules/blob/master/malware/MALW_Mirai_Okiru_ELF.yar#L21) contains a reference to a rule that resides in [this other file](https://github.com/Yara-Rules/rules/blob/master/malware/000_common_rules.yar#L10). 
There wasn't a link for the other file in the general index.yar file so it couldn't find the reference.
I just solved the problem with commit 26f438147aa9892c580c73c1d95d92806609e00a.
Please update your repo and check again. 
If the error is gone please let us know and close the issue.
Thank you very much.

**Comment by jestrada78** [comment]
Thank you!! I realized just yesterday that the possible problem could be that the file 000_common_rules.yar was not included in the index. I added it, but in that case it said that it was duplicated, but when I'm home I'll check and try what you say

**Comment by jholgui** [comment]
@jestrada78, is it solved problem??

**Comment by jestrada78** [comment]
Yes it is.

**Comment by seifreed** [comment]
Closing the issue, as was resolved
