### ISSUE TITLE
Doesn't match?

### ISSUE THREAD

**Issue by TLINDEN** [Yara-Rules/rules#326]
Hello,

I'm new to yara, so maybe I did something dump. So, here's my problem: I have a malicious PDF file, if I scan it with yara with the Yara-Rules ruleset, no rule matches. But the rule `suspicious_version : PDF raw` shall match. I isolated this rule and put it into a separate file, so I can use it with `clamscan`:
```
% yara susversion.yar samples/vir.pdf 
[no output]

% clamscan -d susversion.yar samples/vir.pdf 
samples/vir.pdf: YARA.suspicious_version.UNOFFICIAL FOUND
```

I am using latest yara (version 3.8.1). I also tried the `3.7` branch, just in case current master is instable, to no avail - same result. OS is FreeBSD 10.3.

Could anyone help me please?

Thanks,
Tom

**Comment by jholgui** [comment]
Hello @TLINDEN, i think this question is for yara project .. not? if rule is equal and file is equal .. have you reported this problem to yara project?

**Comment by TLINDEN** [comment]
I have, indeed.
