### ISSUE TITLE
Deployment to RSA NWE 

### ISSUE THREAD

**Issue by FatnLazy** [Yara-Rules/rules#335]
Hi Team,

i would like to implant the YARA rule Executable file as part of our RSA NWE enviornment and i couldnt find any spesific Specs requirment.

It would b awsome if yo could provide me with some specs.

**Comment by Xumeiquer** [comment]
Yara rules are just text file written down in a specific format so there is no way to "compile" them into a binary file. It could be possible to embed the rules as a resource asset in your application so you can use them from that resource. You must have in mind the rules license and if it fits your needs and your application.
