### ISSUE TITLE
Add this rule: Trend Micro MalumPOS from Loki

### ISSUE THREAD

**Issue by jholgui** [Yara-Rules/rules#34]
https://github.com/Neo23x0/Loki/commit/bc6741b779f9b0753945d9920eb2d0e931089a98

**Comment by jholgui** [comment]
Done: https://github.com/Yara-Rules/rules/blob/master/malware/MalumPOS.yar

**Comment by Neo23x0** [comment]
Important: The second rule requires the external "filename" variable. I don't know how you integrate such rules. Better remove it or create another category "rules_with_ext_vars".
