### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [Yara-Rules/rules#351]
The CI setup is currently failing.
Latest build:
https://travis-ci.org/Yara-Rules/rules/builds/535099461

```
modules/androguard.c:608:5: error: too few arguments to function ‘yr_re_match’
     if (yr_re_match(regexp_argument(1), value) > 0) {
     ^
```

I guess we should use the (available) builds or update the dependencies as the CI status of https://github.com/VirusTotal/yara is green.

**Comment by Xumeiquer** [comment]
I will check

**Comment by Xumeiquer** [comment]
This was fixed.
