### ISSUE TITLE
Rule to detect Cobalt Strike instead of FIN7

### ISSUE THREAD

**Issue by halos** [Yara-Rules/rules#355]
https://github.com/Yara-Rules/rules/blob/master/malware/APT_FIN7.yar

Is possibly detecting Cobalt Strike binary instead of a FIN7 binary. FIN7 has reportedly been using Cobalt Strike, so maybe this is the reason for this confusion.

**Comment by jholgui** [comment]
Rule file and rule renamed to APT_Cobalt.yar and Cobalt rule
