### ISSUE TITLE
Rule contradiction

### ISSUE THREAD

**Issue by Inndy** [Yara-Rules/rules#358]
https://github.com/Yara-Rules/rules/blob/76d87e8fb225d2e0bacd76bb00e5c796467f8d7c/malware/TOOLKIT_Chinese_Hacktools.yar#L1693

This rule will match nothing because of contradiction.

**Comment by Xumeiquer** [comment]
Totally agree, two different conditions at offset 0x0 cannot be never true.

**Comment by Xumeiquer** [comment]
This rule was created by https://github.com/Neo23x0 so it may be worth to ask him about it.
