### ISSUE TITLE
Duplicate rules Mimikatz_Memory_Rule_1 Mimikatz_Memory_Rule_2

### ISSUE THREAD

**Issue by timothycovel** [Yara-Rules/rules#36]
including Miscelanea.yar and HackTools.yar causes yara to error out on two duplicate rules:

error: duplicated identifier "Mimikatz_Memory_Rule_2"
error: duplicated identifier "Mimikatz_Memory_Rule_1"

$ grep Mimikatz_Memory_Rule malware/*
malware/HackTools.yar:rule Mimikatz_Memory_Rule_1 : APT {
malware/HackTools.yar:rule Mimikatz_Memory_Rule_2 : APT {
malware/Miscelanea.yar:rule Mimikatz_Memory_Rule_2 : APT {
malware/Miscelanea.yar:rule Mimikatz_Memory_Rule_1 : APT {

**Comment by mmorenog** [comment]
Solved!

Thank you for your help!
