### ISSUE TITLE
File "./malware/APT_FIN7.yar" doesn't exist in the repo.

### ISSUE THREAD

**Issue by ThibaultReuille** [Yara-Rules/rules#363]
It seems that the rule "./malware/APT_FIN7.yar" is included in a few places yet the file is inexistent.

    $ grep -nr APT_FIN7 .
    ./index_w_mobile.yar:164:include "./malware/APT_FIN7.yar"
    ./malware_index.yar:35:include "./malware/APT_FIN7.yar"
    ./index.yar:101:include "./malware/APT_FIN7.yar"
    
    $ file ./malware/APT_FIN7.yar
    ./malware/APT_FIN7.yar: cannot open `./malware/APT_FIN7.yar' (No such file or directory)

**Comment by Djent-** [comment]
It has been renamed to ./malware/API_Cobalt.yar
