### ISSUE TITLE
Big False Positive

### ISSUE THREAD

**Issue by liberodark** [Yara-Rules/rules#366]
clamav updated in ubuntu 18.04

sudo freshclam && sudo clamscan --infected --recursive /

/var/lib/clamav/rfxn.hdb: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/var/lib/clamav/rfxn.ndb: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/var/lib/clamav/rfxn.yara: {HEX}php.gzbase64.inject.452.UNOFFICIAL FOUND
/usr/src/linux-headers-4.15.0-54-generic/arch/x86/purgatory/kexec-purgatory.c: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/local/maldetect/sigs.old/rfxn.hdb: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs.old/md5v2.dat: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs.old/md5.dat: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs.old/hex.dat: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs.old/rfxn.ndb: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs.old/rfxn.yara: {HEX}php.gzbase64.inject.452.UNOFFICIAL FOUND
/usr/local/maldetect/clean/gzbase64.inject.unclassed: {HEX}php.gzbase64.inject.452.UNOFFICIAL FOUND
/usr/local/maldetect/tmp/.runtime.hexsigs.11067: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/tmp/.runtime.hexsigs.1182: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/tmp/.runtime.hexsigs.1195: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/tmp/.runtime.hexsigs.1188: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs/rfxn.hdb: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs/md5v2.dat: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs/md5.dat: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs/hex.dat: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs/rfxn.ndb: YARA.Safe0ver_Shell__Safe_Mod_Bypass_By_Evilc0der_php.UNOFFICIAL FOUND
/usr/local/maldetect/sigs/rfxn.yara: {HEX}php.gzbase64.inject.452.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXClientMonitor.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXShares.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/AskAgentMirror.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXEvent.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXNodeAcquire.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Exception/Configuration.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Exception/Internal.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXLocalSession.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Agent.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXMultimedia.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXPingMonitor.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXCommands.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXUpdate.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXSessionMonitor.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXSudo.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXKeyadd.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXLocalRecordNode.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NodeServerInterface.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXAgentShadow.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXScripts.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXOptionsFile.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXLicense.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/VirtualSessions.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXTools.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXShellCreate.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXError.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXSpanishMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXTranslator.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/Logger.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXSessionType.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXItalianMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXFrenchMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXBegin.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXImage.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXPortugueseMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXRussianMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXRunCommand.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXShellCommands.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXForeign.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXConsole.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXPolishMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXSelector.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXProcess.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXInfo.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXGermanMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXEnglishMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXParser.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXMsg.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXCore.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXPaths.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXLaunchctl.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/Common/NXFile.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXVirtualPrinters.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/nxnode.pl: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXClusterAdd.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXConfiguration.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXLocalRecord.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXAuth.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXSession.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXShell.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXUPnP.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/WaitProcess.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxnode/NXPaths.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXOneTimePassword.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXClusterRemote.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXAsk4Attach.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodeProcess.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXServices/NXHtd.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXServices/NXD.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXServices/NXDaemon.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXClusterParser.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXAsk4Disconnect.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/nxserver.pl: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXEvent.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXSessionParameters.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXLogrotateDB.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXVirtualSession.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXSession2.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXServers.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXLocate.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/SlaveServer.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXConnectionMonitor.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXSubsystem.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NodeCannotConnectToDisplay.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/UserNotInPwDB.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/MaximumNumberVirtualSessionsOnNode.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/Configuration.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NXNodeExecCannotConnect.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NXNodeExecNodeErrorSimple.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NomachineServiceIsNotAvailable.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NXPublicCertNotFound.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/MaximunNumberVirtualSessions.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/Log.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NodeCannotReachRequestedNode.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/Internal.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/UserRefusedToAcceptConnection.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NXNodeExecNotNXUser.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NXUser/NotSystemUser.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NXUser/Base.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NXUser/CheckNotSystemUser.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NXUser/NXCannotLoginByAdministrator.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/NodeCannotStartDisplay.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Exception/MaximunNumberVirtualSessionsForUser.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXShutdown.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXClusterConnect.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodeConfiguration.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXHostsManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXAdministratorsManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXLocalSession.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXTree.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXLimits.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXTest.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXServices.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodeInfo.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodeConnectionMonitor.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXServerDaemon.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXClusterList.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/GetCommandStateMachine.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXPasswd.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXGuestsManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXFirewall.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXClusterConfig.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXUser.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXUpdate.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXLogin.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXServer2Server.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXAnywhereDB.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXPwUserManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXSystemDaemons.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXResources.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXReconnect.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodeCleaner.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXDbusCheckLocal.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXSudo.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodeExec.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXDbusMonitor.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXClusterTools.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXProfiles.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNetInterfaces.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXConnectedUsersManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/KeysManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXPingManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXProfilesDB.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXUpnp.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXBroadcast.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXDebugManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXAnywhereAuth.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/InfoManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXClientConnection.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodes.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXScripts.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXGroups.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodeError.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXUdpControl.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXDbus.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/SessionStartStateMachine.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXClusterDaemon.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXLicense.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXAnywhereClient.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXUtmp.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXClientSystemDaemons.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNssUserManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXLocalSessionNode.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXTools.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXForeignSession.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXProfilesManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXShellCreate.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXError.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXSpanishMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXTranslator.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/Logger.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXSessionType.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXItalianMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXFrenchMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXBegin.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXImage.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXPortugueseMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXRussianMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXRunCommand.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXShellCommands.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXForeign.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXConsole.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXPolishMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXSelector.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXProcess.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXInfo.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXGermanMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXEnglishMessages.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXParser.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXMsg.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXCore.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXPaths.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXLaunchctl.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Common/NXFile.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXFrameBuffer.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXCluster.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXRemoteServer.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodeConnect.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXUsersManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXTerminate.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXSessionList.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXLogrotate.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXConfiguration.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/PhysicSessions.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/handlers/nxserver.pl: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXStartup.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXSessionManager.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXAuth.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXConnectionMonitorTools.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXGssAuth.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXMsg.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/Server.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXNodeGroups.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXAnywhereConfigurator.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXShell.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXPaths.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXSelectNode.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXAnywhereDefault.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXForwardConnection.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXPublicKeyAuth.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/NX/lib/perl/nxserver/NXRemoteNodeControl.pm: YARA.php_malware_hexinject.UNOFFICIAL FOUND
/usr/lib/thunderbird-addons/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}.xpi: YARA.obfuscated_eval.UNOFFICIAL FOUND

That is a big bad detection for false positive.
For information NX is from nomachine.com is you want to test a scan.
Have last version of nomachine in x64 deb.

**Comment by liberodark** [comment]
That is Thunderbird extension is not a virus :

{e2fda1a4-762b-4020-b5ad-a41df1933103}.xpi

[file.zip](https://github.com/Yara-Rules/rules/files/4016160/file.zip)

**Comment by plusvic** [comment]
This repository doesn't contain any signatures, this is about the YARA engine itself, but we don't provide signatures for specific malware. Those signatures are probably maintained by ClamAV.

**Comment by Xumeiquer** [comment]
Is this something related to a Yara rule that matches a false positive?
