### ISSUE TITLE
[BUG]antidebug_antivm.yar when checked by clamscan

### ISSUE THREAD

**Issue by dominicraf** [Yara-Rules/rules#370]
This file throws an error with clamd ClamAV 0.102.1

To reproduce:
```
cd /tmp
wget https://github.com/Yara-Rules/rules/raw/master/antidebug_antivm/antidebug_antivm.yar
clamscan -d antidebug_antivm.yar
```

Output:
LibClamAV Error: yyerror(): antidebug_antivm.yar line 528 undefined identifier "pe"
LibClamAV Error: yyerror(): antidebug_antivm.yar line 543 undefined identifier "pe"
LibClamAV Error: yyerror(): antidebug_antivm.yar line 559 undefined identifier "pe"
LibClamAV Error: yyerror(): antidebug_antivm.yar line 575 undefined identifier "pe"
LibClamAV Error: yyerror(): antidebug_antivm.yar line 588 undefined identifier "pe"
LibClamAV Error: yyerror(): antidebug_antivm.yar line 634 undefined identifier "pe"
LibClamAV Error: yyerror(): antidebug_antivm.yar line 645 undefined identifier "pe"
LibClamAV Warning: load_oneyara: yara rule contains no supported strings, skipping YARA.WindowsPE
LibClamAV Warning: cli_loadyara: failed to parse or load 8 yara rules from file antidebug_antivm.yar, successfully loaded 47 rules.
clamscan: yara_exec.c:177: yr_execute_code: Assertion `sp == 0' failed.
Aborted (core dumped)

**Comment by dominicraf** [comment]
On reflection, I realise this may be down to limitations in the ClamAV Yara implementation rather than a bug in `antidebug_antivm.yar`.  See [here](https://www.clamav.net/documents/using-yara-rules-in-clamav).

**Comment by Xumeiquer** [comment]
The error is because the Yara version you are using was not compiled with PE support.
