### ISSUE TITLE
[BUG] RAT_PoetRATDoc.yar and RAT_PoetRATPython.yar both define same rule

### ISSUE THREAD

**Issue by MJJoker** [Yara-Rules/rules#380]
**Describe the bug**
the two rule-files down below define the rule name "PoetRat", which may lead to errors  when running "index.yar"
* malware/RAT_PoetRATDoc.yar
* malware/ .yar

**To Reproduce**
1. navigate to the rules folder
2. run "yara index.yar"

**Expected behavior**
all rules are loaded and the target files are scanned

**Desktop (please complete the following information):**
 - OS: Ubunut 18.04.4
 - Yara version 3.7.1

**Additional context**
the exact error message is:
/tmp/rules-master/./malware/RAT_PoetRATPython.yar(1): error: duplicated identifier "PoetRat"

**Comment by Xumeiquer** [comment]
This was fixed in #379
