### ISSUE TITLE
Remove highly false-positive rules

### ISSUE THREAD

**Issue by brad-accuvant** [Yara-Rules/rules#39]
While having a large number of rules looks impressive, having rules with extremely high false-positive rates is counter-productive.  Packer rules like Armadillov171 match on standard MSVC entrypoints, other tiny byte-matchers like the cpuid/rdtsc rules are easily matched in instruction immediates, relative offsets, data references, or obfuscated data.  It would be nice to use this ruleset in an auto-update fashion, but the false positives hinder adoption and usually end up getting cited in academic research for incorrect statistics on features of the current malware landscape.

**Comment by jholgui** [comment]
Hi @brad-accuvant, we are totally agree with your issue. Now, we are building a repository with binaries to test the ruleset. In any case, if the community reports false positives we will check it. The next target of @yararules is improve the usefullness. 

Do you have a list with rules with extremely high false positives? 

Thank you for your feedback!

**Comment by brad-accuvant** [comment]
Just a small initial list:
Check_unhandledExceptionFiler_iat
check_RaiseException_iat
maldoc_function_prolog_signature
maldoc_structured_exception_handling
maldoc_suspicious_strings
java
Armadillov171
DebuggerTiming__PerformanceCounter
DebuggerTiming__Ticks
DebuggerOutput__String
DebuggerException__UnhandledFilter
DebuggerPattern__RDTSC
DebuggerPattern__CPUID
DebuggerPattern__SEH_Saves
DebuggerPattern__SEH_Inits
APT1_payloads

In general, the maldoc signatures are problematic as they don't exempt PEs.  Signatures with match bytes of 3 or less should be thrown out.  The AP1_payloads signature only requires one match and contains things like "d.exe", "p.exe".

**Comment by jovimon** [comment]
Hi Brad,
First of all, thank you very much for your suggestions.
Excuse us for the delay, I've just pushed commit 84a474ce35fe3b8ee64ebe150dcf2f433ac65939 which comments out all the rules in your list. We will review the general matches you pointed out and update the ruleset soon.
Regards.
