### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 2d4d** [Yara-Rules/rules#401]
**Describe the bug**
It's not clear to me, where the error is:

![grafik](https://user-images.githubusercontent.com/46819580/105580333-0aa01500-5d8c-11eb-9185-be880740f3df.png)

**To Reproduce**
make PR

**Expected behavior**
clear error message

**Comment by Xumeiquer** [comment]
PR merged. I think it is because of the token for pushing the changes it was revoked.
