### ISSUE TITLE
Rulesets for mobile_malware is empty ,But I really need it

### ISSUE THREAD

**Issue by lizhixiang0** [Yara-Rules/rules#402]
**Is your feature request related to an article or investigation? Please describe.**
A clear and concise description of what the article or investigation is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Xumeiquer** [comment]
You can find them in the [deprecated directory](https://github.com/Yara-Rules/rules/tree/master/deprecated).
