### ISSUE TITLE
@Auxilus I believe we want to cross compile the packages in the docker image and get the the debs from there. You then need docker.

### ISSUE THREAD

**Issue by raminam6488** [Yara-Rules/rules#406]
@Auxilus I believe we want to cross compile the packages in the docker image and get the the debs from there. You then need docker. 

@fornwall I could setup and maintain the repo as well, preferably at grimler.se as github.io's caching makes it none-ideal for package hosting.
Would this be an acceptable setup? 

_Originally posted by @Grimler91 in https://github.com/termux/termux-root-packages/issues/1#issuecomment-355900146_

**Comment by raminam6488** [comment]
> @Auxilus I believe we want to cross compile the packages in the docker image and get the the debs from there. You then need docker. 
> 
> @fornwall I could setup and maintain the repo as well, preferably at grimler.se as github.io's caching makes it none-ideal for package hosting.
> Would this be an acceptable setup? 
> 
> _Originally posted by @Grimler91 in https://github.com/termux/termux-root-packages/issues/1#issuecomment-355900146_

**Comment by Auxilus** [comment]
![giphy](https://user-images.githubusercontent.com/23075789/108953686-a07fd600-7691-11eb-90ae-6ad0807dbb5f.gif)
