### ISSUE TITLE
Yara Rules Compatible With IoT Devices Intents

### ISSUE THREAD

**Issue by jpsla-iscteiul** [Yara-Rules/rules#408]
Hello,

I am studying yara rules in the context of a master thesis and i have a question that is the following:

Can IoT Devices Intents be specified through Yara Rules? I am having trouble finding information that answers me this question and I would like if you can provide me with an answer.

Best Regards,
João Lola

**Comment by chrisdoman** [comment]
Hi,

 What do you mean by "Intents" please?

Thanks,

**Comment by jpsla-iscteiul** [comment]
Thanks but i have figure it out. Thank you for your interest in the matter.
