### ISSUE TITLE
False Positives for GLASSES?

### ISSUE THREAD

**Issue by Nilstorm** [Yara-Rules/rules#422]
Novice YARA user here:

Ive run the malware ruleset on my Sys32 Dir without -r and come across alot of positives (+extra counts) for GLASSES and GLASSESCode

  Most matches are with Direct X DLLS but assume its just coincidental matches. Would appreciate knowing more about this from someone who understands the thread matches for this (APT_Glasses.yar). Maybe im infected?

![Screenshot (199)](https://user-images.githubusercontent.com/52558616/141932847-6f7132d9-ae40-4fb6-aa9b-5ca53d00540e.png)

**Comment by RandomRhythm** [comment]
I’ll point out that this is marked as a bug from a repository perspective. However, I’d like to address your question of infection with some further information. The rule GlassesCode that is causing both the GlassesCode and GlassesString matches is prone to false-positives.  I wouldn’t trust that rule alone to identify if a file is malicious.
