### ISSUE TITLE
"import androguard" raises error inside YARA rule

### ISSUE THREAD

**Issue by shivang1989** [Yara-Rules/rules#45]
I tried importing androguard in python and it is working absolutely fine but when I imported "androguard" in yara, it raises an error saying [error: unknown module "androguard" ] 

On searching related to "imports" in yara, it leads to using yara in python. 
What am I doing wrong ? 
Why am I not able to import androguard inside yara ? 

Please assist. Any help is appreciated. TIA

P.S - Androguard library is installed. I am using Yara 3.4.0 .

**Comment by plutec** [comment]
Jose Vila answered:
Hi Shivang,

Unfortunately androguard module isn't public yet. People at koodous.com are working hard to publish it as soon as possible.

You are not the first person asking this question, so we put a disclaimer on every file importing androguard module.

We hope the module is published soon and we all can benefit from their excellent work.

Regards,

Jose Vila.

**Comment by mmorenog** [comment]
Hi guys,

Androguard module used in this rule file is under development by people at https://koodous.com/.

You can get it, along with installation instructions, at https://github.com/Koodous/androguard-yara

Regards,
