### ISSUE TITLE
Undefined identifier

### ISSUE THREAD

**Issue by dforce** [Yara-Rules/rules#53]
Using the rules I receive some syntax errors :
- Miscelanea.yar(90): undefined identifier "uint16be"
- general_cloaking.yar(56): undefined identifier "filepath"

What am I missing to resolve these messages ?

Thanks
Miguël

**Comment by frbapolkosnik** [comment]
For the first one:  yara2.0+ should probably do it. For the second one, if you are checking files against rules, you can define a variable for filepath, and pass it to yara.

To quote from http://yara.readthedocs.org/en/latest/yarapython.html
"""
If you are using external variables in your rules you must define those externals variables either while compiling the rules, or while applying the rules to some file. To define your variables at the moment of compilation you should pass the externals parameter to the compile method. For example:

rules = yara.compile('/foo/bar/my_rules’,
  externals= {'var1': 'some string’, 'var2': 4, 'var3': True})
"""

**Comment by dforce** [comment]
Ok, thanks for the information.
