### ISSUE TITLE
malware.yar missing

### ISSUE THREAD

**Issue by karolpivo** [Yara-Rules/rules#60]
Hi, 

I don't seem to be able to see the mlware.yar file. 

what is the best way to create one from all the rules in the malware category? I tried the cat * > malware.yar but the resulting rule file gives errors 

thanks!

**Comment by jholgui** [comment]
Hi @karolpivo,

From now, you can create malware.yar with those commands:

$ git clone https://github.com/Yara-Rules/rules.git
$ cd rules/malware
$ cat *.yar > /tmp/malware.yar.

We have deleted the rules with external variables and duplicated rules. 

Thank you very much!! 

Regards!

**Comment by karolpivo** [comment]
Hi jholgui,

I tried but still get the following error:

root@kali-kp:~/Downloads/rules# yara -r malware.yar /tmp/
malware.yar(13011): error: undefined identifier "uint16be"

After removing this rule it's working fine

rule Cloaked_as_JPG {
        meta:
                description = "Detects a cloaked file as JPG"
                author = "Florian Roth (eval section from Didier Stevens)"
                date = "2015/02/29"
                score = 70
        strings:
                $ext = "extension: .jpg"
        condition:
                $ext and uint16be(0x00) != 0xFFD8

Thanks
karol

**Comment by frbapolkosnik** [comment]
Which version of Yara are you using?

**Comment by karolpivo** [comment]
3.1 - I see, it's not supported in this version ? I'll get myself updated


thanks
