### ISSUE TITLE
Undefined identifier in malicious_document.yar

### ISSUE THREAD

**Issue by msapiro** [Yara-Rules/rules#78]
Clamav reports:

LibClamAV Error: yyerror(): /var/lib/clamav/malicious_document.yar line 245 undefined identifier "uint32be"

**Comment by jholgui** [comment]
yara version? 

http://yara.readthedocs.org/en/latest/writingrules.html

uint32be is a yara keyword.

**Comment by msapiro** [comment]
This is with Clamav 0.99.0.

Apparently this is an issue with the Clamav implementation of YARA. I now see their docs (sec 3.11 of https://github.com/vrtadmin/clamav-devel/blob/master/docs/signatures.pdf ) say

YARA modules are not yet supported by ClamAV. This includes the “import” keyword and any YARA module-specific keywords.

Sorry for the noise.
