### ISSUE TITLE
Undefined identifier in antidebug.yar

### ISSUE THREAD

**Issue by msapiro** [Yara-Rules/rules#79]
Clamav reports:

LibClamAV Error: yyerror(): /var/lib/clamav/antidebug.yar line 497 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug.yar line 512 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug.yar line 528 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug.yar line 544 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug.yar line 557 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug.yar line 603 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug.yar line 614 undefined identifier "pe"
LibClamAV Error: cli_loadyara: failed to parse rules file /var/lib/clamav/antidebug.yar, error count 7

**Comment by jholgui** [comment]
yara version? 

Your yara has to support PE module.

http://yara.readthedocs.org/en/latest/modules/pe.html

**Comment by Neo23x0** [comment]
As far as I know "modules" are not supported by ClamAV - see
http://blog.clamav.net/2015/06/clamav-099b-meets-yara.html

**Comment by msapiro** [comment]
http://blog.clamav.net/2015/06/clamav-099b-meets-yara.html is about clamav 0.99b1, but apparently the same limitation is in the final 0.99 release.

Sorry for the noise.

**Comment by trasherdk** [comment]
I'm on clamav-0.99.2-x86_64 (Slackware)
, and seeing:
` LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 497 undefined identifier "pe" `

all over the place.
